Support for webpack 5
mastilver/dynamic-cdn-webpack-plugin pull request #71
Opened 2021-07-04 03:23 UTC by kmalakoff

I was using this plugin for webpack 4 and wanted to use it for webpack 5.

If you are interested in accepting with pull request, there are a few points of note:

- I republished it under @effortlessmotion/dynamic-cdn-webpack-plugin so we'd need to change the module name back
- I added a line to the README.md warning this is a fork when I published it under a different org
- I made it work with Node 10 like webpack guarantees as a compatible version 
- I removed ava and replaced it with tape as I couldn't get the latest ava to test on Node 10
- I removed babel and es6 modules to make this simpler to test, run, and publish without extra steps. Webpack 5 uses require for backwards compatibility without transpiling

2021-07-10 20:50 UTC, ChocolateLoverRaj commented
@kmalakoff can you please link this to say it fixes #71?

2021-07-11 00:54 UTC, kmalakoff commented
This fixes [issue 70](https://github.com/mastilver/dynamic-cdn-webpack-plugin/issues/70)

2021-07-12 08:26 UTC, jmfrancois commented on readme.md
> +Warning: This module is a fork from [https://github.com/mastilver/dynamic-cdn-webpack-plugin](https://github.com/mastilver/dynamic-cdn-webpack-plugin) to support Webpack 5.
should not be here :)

2021-07-15 09:11 UTC, mg-83 commented on readme.md
> +Warning: This module is a fork from [https://github.com/mastilver/dynamic-cdn-webpack-plugin](https://github.com/mastilver/dynamic-cdn-webpack-plugin) to support Webpack 5.
as he said in his comment

2021-07-15 11:58 UTC, mg-83 commented
@mastilver are you still updating this?

2021-07-29 16:44 UTC, aulisius commented
Hi @kmalakoff ! One of the maintainers here :)

Thanks for the huge help in adding Webpack 5 support to this plugin. Much appreciated.

I'm unable to reach @mastilver (I'll try again) so I'm unsure as to how we would publish to npm but I don't think that should stop us from merging this into the codebase.

I'll go through your PR and get back on this asap. If in the event we aren't able to push this to npm, I think we can add a message to the README pointing to the `@effortlessmotion/dynamic-cdn-webpack-plugin` for now.

2021-10-05 18:51 UTC, richardantao commented
Hi @aulisius, any updates?

2021-10-06 05:45 UTC, aulisius commented
Hi @richardantao, you can use `@effortlessmotion/dynamic-cdn-webpack-plugin` package which supports webpack 5.

2022-03-25 20:55 UTC, elamperti requested changes
@kmalakoff First of all, thanks for taking the time to make all the required changes to update this package! I've noticed some changes that may not be directly related to the PR and some things that could use clarification.

In regard to your fork, it's great to have an alternative! This PR should keep all references to the original package as they are, so if this PR is accepted the changes can be reflected for all users.

It could be useful if @mastilver considers making you (or anyone else who may have the time and knowledge) maintainer of the repo to keep the project alive.

2022-03-25 20:55 UTC, elamperti commented on .travis.yml
> +      os: windows
What does it add to test on Windows in the context of this plugin?

2022-03-25 20:55 UTC, elamperti commented on package.json
> +  "name": "@effortlessmotion/dynamic-cdn-webpack-plugin",
This shouldn't change in this PR.

2022-03-25 20:55 UTC, elamperti commented on package.json
> +    "url": "https://github.com/mastilver"
This is up to the author and irrelevant to the PR

2022-03-25 20:55 UTC, elamperti commented on src/index.js
> +} catch (_) {}
This doesn't improve legibility and I don't see any improvement in performance either.

2022-03-25 20:55 UTC, elamperti commented on src/index.js
> +        if (exclude && only) throw new Error('You can\'t use \'exclude\' and \'only\' at the same time');
This formatting change isn't relevant to the PR (and may be opposed to the style the author wants to use)

2022-03-25 20:55 UTC, elamperti commented on src/index.js
> +            if (this.verbose) console.log(`❌ '${modulePath}' couldn't be found, please add it to https://github.com/mastilver/module-to-cdn/blob/master/modules.json`);
Same as above, and in this case the `console.log` line is already long so it difficults reading the whole line on small or split screens.

2022-04-21 07:34 UTC, jmfrancois commented
FYI we have never been able after multiple attempts to contribute back to this module with module-to-cdn.
We have decided to fork it under Talend github organisation.
The fork is public and we have deployed sites in production with custom CDN based on this fork.
https://github.com/Talend/ui/tree/master/fork

We have added multiple features to answer needs for deployments:
* possibility to have other CDN than unpkg.
* url formating
* add metadata to html webpack plugin
* fix bug around dependencies management
* introduce a dependencies.json file along UMDs

We plan to add webpack 5 support this year

2022-06-11 09:41 UTC, cosmincc commented
Would be great to have this done. I'm sure the maintainers could update the pull request and fix the issues directly, no?
Can anyone else help speed this up?

2022-06-12 10:43 UTC, aulisius commented
There's no blockers to merge this PR but only @mastilver holds the access to publish on npm. So, even if the PR is merged, it wouldn't be updated on npm

2022-10-12 09:54 UTC, Nishchit14 commented
@mastilver would be grateful if you can publish it. thank you.

2023-06-12 23:27 UTC, CSDev0 commented
author is dead or what? this project is saddly no longer maintained as i see.

2023-06-13 02:46 UTC, merged